import type { Metadata } from "next";
import { Roboto_Mono, Inter, Cairo, Lemonada } from "next/font/google";
import { hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { setRequestLocale } from "next-intl/server";
import { cn } from "@/lib/utils/tailwind-merge";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  weight: ["400", "500", "600", "700"],
});

const cairo = Cairo({
  subsets: ["latin"],
  variable: "--font-cairo",
  weight: ["400", "500", "600", "700"],
});

const lemonada = Lemonada({
  subsets: ["latin"],
  variable: "--font-lemonada",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: React.ReactNode;
  params: { locale: string };
};

export default function LocaleLayout({ children, params }: LayoutProps) {
  const { locale } = params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);

  return (
    <div
      dir={locale === "ar" ? "rtl" : "ltr"}
      className={cn(
        locale === "ar" ? cairo.className : robotoMono.className,
        robotoMono.variable,
        inter.variable,
        cairo.variable,
        lemonada.variable,
        "antialiased",
      )}
    >
      {children}
    </div>
  );
}
